### ISSUE TITLE
Update .travis.yml 

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/Wind_multipliers#10]
Need to update the .travis.yml file to change the way python modules are installed. See the .travis.yml file from [TCRM](https://github.com/GeoscienceAustralia/tcrm/blob/v2.0/.travis.yml) for an example. 

Note we should retain the most recent change to exclude the `notebooks` branch

**Comment by CEKrause** [comment]
Build successful! 
I will close this issue for now, but re-open if it continues.
