### ISSUE TITLE
Input file formats are fixed

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/Wind_multipliers#2]
Input file formats are fixed as Erdas Imagine files (".img") - see http://www.gdal.org/frmt_hfa.html

Need to make the interface more flexible to permit alternative input formats

**Comment by CEKrause** [comment]
I believe that fixing issue #1 also fixed this issue. The code is no longer hard coded to expect a certain file name, so the whole file name (including the suffix) can be varied. 
It seems that all file types able to be used with GDAL should now be able to be read into the code. 
I will write some unit tests to check this.

**Comment by CEKrause** [comment]
Unit tests and exception/error handling for reading in the DEM files has been added. 
Other file formats can now be read in, and an .img file is no longer required. This has been tested with GTiff. 
netCDF files are not supported, but will be caught now in error handling to alert the user.
